### ISSUE TITLE
I'm really confused.

### ISSUE THREAD

**Issue by GammaRage** [NeKitDS/gd.rpc#10]
I have the gd.py libraries installed, but trying to do  `py -3 -m pip install -U gd.rpc` still refuses to work because it's not detected. Why?

**Comment by DenoXen** [comment]
You have installed Python, and added to path?

**Comment by GammaRage** [comment]
Yes.

**Comment by NeKitDS** [comment]
I suppose you have installed gd.py version from PyPI, while some features used here are unstable. Use this:
```sh
python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
```
And then try installing again.

**Comment by GammaRage** [comment]
Ah, thank you. I'll try this later and get back to you.
