### ISSUE TITLE
Strange mistake

### ISSUE THREAD

**Issue by StinkyUwU** [NeKitDS/gd.rpc#3]
Well, I downloaded the .exe from the rich presence but when I open it it stays black for a long time like 8 minutes and then "Could not create initial factory. C: \ Users \ David \ AppData \ Local \ Temp \ _MEI73842 \ gd \ assets \ icon_sheet.png was not found.
Running gd.rpc v.0.1.8 ... Press [Ctrl + C] to stop. "And it does nothing ... What do I do?

**Comment by NeKitDS** [comment]
This is somewhat expected behavior because for some reason PyInstaller is not correctly including images gd.py uses. I will try to look into how to fix this error, but it's not critical so the rich presence runs.

**Comment by StinkyUwU** [comment]
> This is somewhat expected behavior because for some reason PyInstaller is not correctly including images gd.py uses. I will try to look into how to fix this error, but it's not critical so the rich presence runs.

thanks

**Comment by StinkyUwU** [comment]
> This is somewhat expected behavior because for some reason PyInstaller is not correctly including images gd.py uses. I will try to look into how to fix this error, but it's not critical so the rich presence runs.

Well despite this error the rich presence doesn't work for me:/
