### ISSUE TITLE
Unfortunately it can't find a version of gd.py to satisfy the requirement

### ISSUE THREAD

**Issue by MrMelon54** [NeKitDS/gd.rpc#4]
ERROR: Could not find a version that satisfies the requirement gd.py>=1.0.0b0 (from gd.rpc==0.2.7) (from versions: 0.0.1.1, 0.0.3, 0.0.3.1, 0.0.3.2, 0.0.3.3, 0.0.3.4, 0.0.3.5, 0.0.3.6, 0.0.3.7, 0.0.4.0, 0.0.4.1, 0.0.4.2, 0.0.4.3, 0.0.5.0, 0.0.6, 0.0.6.1, 0.7.0b2, 0.7.0rc1, 0.7.0rc2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0a1, 0.9.0a2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10.0a0, 0.10.0a3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.5)
ERROR: No matching distribution found for gd.py>=1.0.0b0 (from gd.rpc==0.2.7)

**Comment by NeKitDS** [comment]
Hey there! Problem is that gd.rpc requires latest version of gd.py, which can be installed from GitHub:
```sh
python -m pip install -U https://github.com/NeKitDS/gd.py/archive/master.zip
```
