### ISSUE TITLE
not working with GDPS

### ISSUE THREAD

**Issue by N4Cl-G4ming** [NeKitDS/gd.rpc#5]
I'm trying to change the code so it can redirect to a GDPS for my own use but it doesn't work. is there a way to fix that?

**Comment by NeKitDS** [comment]
Hey there! Can you please elaborate on the "redirect to GDPS" part? And what exactly does not work on GDPS?

**Comment by N4Cl-G4ming** [comment]
the RPC doesn't work when i change the **`GD_PROCESS="GeometryDash.exe`** to **`GD_PROCESS="VPS.exe`** even though i have the GDPS running.

**Comment by NeKitDS** [comment]
Sounds like you are using outdated version of the library, because ``GD_PROCESS`` was deprecated and removed.

Updated version of gd.py and gd.rpc will attempt to find GD window by "Geometry Dash" title.

In the *new* source, I suppose you can write ``memory = gd.memory.get_memory("VPS.exe", load=False)`` in order to make it load correctly.

**Comment by PhyteGD** [comment]
You can also change the window name of your exe.

**Comment by NeKitDS** [comment]
I know. By the way, previous versions of gd.rpc were sending requests to the server, which surely have caused it to not work correctly with your GDPS, but now gd.rpc does not send *any* requests **at all**, which makes it lighter and more compatible.

**Comment by NeKitDS** [comment]
This commit: https://github.com/NeKitDS/gd.rpc/commit/c7186ba4a06b8c6cbefb72ada3e492bb7a1ac3fa adds ability to change process name through the config.

**Comment by N4Cl-G4ming** [comment]
It works now. thanks for helping me out.

(also one final question, can i use the rich presence and modify its files so it can be compatible with all gdps' out there?)

**Comment by DenoXen** [comment]
you can't.

**Comment by NeKitDS** [comment]
Essentially, again, since the RPC does not request any data from the servers, and falls back to find the game by window title, it should work with most GDPS that don't have their offsets messed up.
