### ISSUE TITLE
Windows Blocking File

### ISSUE THREAD

**Issue by aZephy** [NeKitDS/gd.rpc#6]
Virustotal detected a python clipbanker and windows completely blocked the app from running. I would run it but-

**Comment by MrMelon54** [comment]
If you don't want to run it then install python and run the python code directly.

**Comment by SpookyBear0** [comment]
@aZephy  When using the exe virus detectors may find a "virus" in the code even though there is none. If you don't want your antivirus going off I suggest doing what @MrMelon54 said. Also, antivirus's do not work, most of the time its only blocking stuff you want and it almost never blocks actual virus's.

**Comment by NeKitDS** [comment]
Joining this conversation, it's funny how an antivirus can find something like *this* in an executable. Anyways, as Spooky and Melon have mentioned, there are two ways: either make your antivirus ignore the RPC file, or install python and packages, then run the project.

**Comment by aZephy** [comment]
> Joining this conversation, it's funny how an antivirus can find something like _this_ in an executable. Anyways, as Spooky and Melon have mentioned, there are two ways: either make your antivirus ignore the RPC file, or install python and packages, then run the project.

thank you for not making fun of me for not understanding this lo, also i need to make another issue rq

**Comment by MrMelon54** [comment]
You can't expect everyone to understand everything. At least you understand now 😄.
