### ISSUE TITLE
Percentage not working

### ISSUE THREAD

**Issue by aZephy** [NeKitDS/gd.rpc#7]
{percent} doesnt update on discord, it just shows 0% the whole time

**Comment by MrMelon54** [comment]
Maybe Discord just isn't showing the updates or it's an actual bug and I'll just leave the developer to sort it out or write a fix for it myself.

**Comment by aZephy** [comment]
> Maybe Discord just isn't showing the updates or it's an actual bug and I'll just leave the developer to sort it out or write a fix for it myself.

well discord updates everything except for the percentage accordingly, so it might be the rpc.

**Comment by MrMelon54** [comment]
Yeah there is probably a problem with the rpc then

**Comment by NeKitDS** [comment]
We need to test it with python, can you install it and the latest version of gd.py and run
```python
import gd

memory = gd.memory.get_memory()

print(memory.read_at(0x10, memory.read_type(
    memory.ptr_type, 0x3222D0, 0x164, 0x3C0, 0x12C
)).data)
```
while in the level?

You can install latest version with
```sh
python -m pip install https://github.com/NeKitDS/gd.rpc
```

**Comment by NeKitDS** [comment]
Okay, I did some research, and turns out I wrote string address fetching incorrectly, which was fixed in the recent gd.py update. You can install it via:
```sh
python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
```
@aZephy

**Comment by NeKitDS** [comment]
Also, current percentage in gd.py uses the string that is displayed on the screen, so maybe that is the issue. I am researching a better way now!

**Comment by NeKitDS** [comment]
Alright, I think I found one. Needs a bit of testing, but it should be good.

**Comment by NeKitDS** [comment]
1e4429393cae5fc0998b4c95882030162d0923e0 fixes percentage displaying. Closing this issue now.
