### ISSUE TITLE
Could not find a version

### ISSUE THREAD

**Issue by aZephy** [NeKitDS/gd.rpc#8]
ERROR: Could not find a version that satisfies the requirement gd.py>=1.0.0rc0 (from gd.rpc==0.5.0) (from versions: 0.0.1.1, 0.0.3, 0.0.3.1, 0.0.3.2, 0.0.3.3, 0.0.3.4, 0.0.3.5, 0.0.3.6, 0.0.3.7, 0.0.4.0, 0.0.4.1, 0.0.4.2, 0.0.4.3, 0.0.5.0, 0.0.6, 0.0.6.1, 0.7.0b2, 0.7.0rc1, 0.7.0rc2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0a1, 0.9.0a2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10.0a0, 0.10.0a3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.5)
ERROR: No matching distribution found for gd.py>=1.0.0rc0 (from gd.rpc==0.5.0)

i have no idea what this means or how to fix it, but it comes from me running \gd.rpc>python -m pip install -U .

i have installed gd.py version 1.0.something, im not sure.

**Comment by aZephy** [comment]
> ERROR: Could not find a version that satisfies the requirement gd.py>=1.0.0rc0 (from gd.rpc==0.5.0) (from versions: 0.0.1.1, 0.0.3, 0.0.3.1, 0.0.3.2, 0.0.3.3, 0.0.3.4, 0.0.3.5, 0.0.3.6, 0.0.3.7, 0.0.4.0, 0.0.4.1, 0.0.4.2, 0.0.4.3, 0.0.5.0, 0.0.6, 0.0.6.1, 0.7.0b2, 0.7.0rc1, 0.7.0rc2, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0a1, 0.9.0a2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10.0a0, 0.10.0a3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.5)
> ERROR: No matching distribution found for gd.py>=1.0.0rc0 (from gd.rpc==0.5.0)
> 
> i have no idea what this means or how to fix it, but it comes from me running \gd.rpc>python -m pip install -U .
> 
> i have installed gd.py version 1.0.something, im not sure.

i could also literally just be dumb

**Comment by NeKitDS** [comment]
```sh
python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
```
This should get you the version enough for running.
You get that error because the all gd.py rewrites are experimental and I can't be sure about their safety. Therefore, versions starting from 1.0.0dev were not uploaded to PyPI.

**Comment by aZephy** [comment]
> ```shell
> python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
> ```
> 
> This should get you the version enough for running.
> You get that error because the all gd.py rewrites are experimental and I can't be sure about their safety. Therefore, versions starting from 1.0.0dev were not uploaded to PyPI.

thanks, it worked!
