### ISSUE TITLE
Application not working, but command is

### ISSUE THREAD

**Issue by aZephy** [NeKitDS/gd.rpc#9]
Opening the installed application of gdrpc from pyinstaller instantly crashes. It opens up the gdrpc 'cmd prompt' looking thing, and then closes a few seconds later. Running gd.rpc from Python38\gd.rpc> completely works, just not the executable file.

I'm really sorry im having so much issues, i tend to mess things up a lot

**Comment by NeKitDS** [comment]
Hm, I am not sure, did you compile it on your own? One thing you can try is navigating to the executable file, opening command prompt and running the exe from it.
